spring:
  profiles:
    #  Indicate the environment
    active: dev
  application:
    #  projectName
    name: bin_fresh_recruit_backend

  #    Swagger-UI starts 404 problem, add interception
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8081
  #  Uniform request prefix
  servlet:
    context-path: /bin_fresh_recruit

# Automatic hump switching is prohibited
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #    Open database query log
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # Automatically skip data that has been logically deleted（Need to be used in conjunction with @ TableLogic）
  global-config:
    db-config:
      logic-delete-field: is_delete # Entity field name for global logical deletion (since 3.3.0, step 2 can be ignored after configuration)
      logic-delete-value: 1 # Logical deleted value (default is 1)
      logic-not-delete-value: 0 # Logical undeleted value (default is 0)
      id-type: auto # Self increasing ID
  # 日志
logging:
  config: classpath:logback-spring.xml
  #  Record all SQl
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            mapper:
              BaseMapper: debug
      bin:
        bin_fresh_recruit_backend:
          mapper: debug

# Third party service connection replicated locally（Regularly replace domain names within 30 days）
qiniu:
  # Public key
  accessKey: AInw755zXpHzJg8xC-ZIbgRwR_0QW7F7FikmrZU_
  # Private key
  secretKey: p7YuVGxXvyKszPNthjgfd5nvUraiqu0CvQzAFFsp
  # Storage space name
  bucketName: bin-fresh-recruit-backend
  # Domain name/path
  path: http://s9zeur713.hn-bkt.clouddn.com
  # The file names stored in the space do not need to be deleted（With diagonal rods["/"]）
  documentName: bin_fresh_recruit_backend/

aliyun:
  #  Access key
  accessKeyId: LTAI5tGAwd5LAJcQR2xYUmNG
  #  Secret key
  accessKeySecret: xdxPUgh7Fgdiks0aZEg4UhbDV99YKk
  #  endpoint
  endpoint: oss-cn-guangzhou.aliyuncs.com
  #  buckentName
  bucketname: bin-fresh-recruit-backend
  signName: 校招通
  templateCode: SMS_464051255