spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bin-study.mysql.database.azure.com:3306/db_bin_fresh_job?serverTimezone=Asia/Shanghai
    username: super
    password: Abinbin123!!
  #    Session timeout (in minutes)
  session:
    timeout: 604800
    store-type: redis

  #    Redis配置
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    database: 0
    redissonDataBase: 2
    timeout: 60s
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3600ms