spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_bin_fresh_job?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #    Session timeout (in minutes)
  session:
    timeout: 4320
    store-type: redis

  #    Redis配置
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    database: 0
    redissonDataBase: 2