spring:
  profiles:
    #  Indicate the environment
    active: dev
  application:
    #  projectName
    name: bin_fresh_recruit_backend

  #    Swagger-UI starts 404 problem, add interception
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8081
  #  Uniform request prefix
  servlet:
    context-path: /bin_fresh_recruit

# Automatic hump switching is prohibited
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #    Open database query log
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # Automatically skip data that has been logically deleted
  global-config:
    db-config:
      logic-delete-field: isDelete # Entity field name for global logical deletion (since 3.3.0, step 2 can be ignored after configuration)
      logic-delete-value: 1 # Logical deleted value (default is 1)
      logic-not-delete-value: 0 # Logical undeleted value (default is 0)
  # 日志
logging:
  config: classpath:logback-spring.xml
  #  Record all SQl
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            mapper:
              BaseMapper: debug
      bin:
        bin_fresh_recruit_backend:
          mapper: debug

qiniu:
  # Public key
  accessKey: AInw755zXpHzJg8xC-ZIbgRwR_0QW7F7FikmrZU_
  # Private key
  secretKey: p7YuVGxXvyKszPNthjgfd5nvUraiqu0CvQzAFFsp
  # Storage space name
  bucketName: bin-fresh-recruit-backend
  # Domain name/path
  path: http://s4pyawr5m.hn-bkt.clouddn.com
  # The file names stored in the space do not need to be deleted
  documentName: bin-fresh-recruit-backend/